### ISSUE TITLE
Feature: Mobile Steppers

### ISSUE THREAD

**Issue by roelbarreto** [roelbarreto/md-steppers#10]
![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0VdkdHZl9FNDV6R28/components_acux_stepper_mbltypog.png)

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0VZV9JT1hKVjJwcFE/components_acux_stepper_mbldots.png)

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0VTUlvaXVPZEJ2LUU/components_acux_stepper_mblprgrssbr.png)

**Comment by VesperDev** [comment]
+1

**Comment by ighormartins** [comment]
+1

**Comment by arnieraju** [comment]
+1

**Comment by adrianandreias** [comment]
+1

**Comment by alonbrims** [comment]
+1
