### ISSUE TITLE
md-steppers in NPM

### ISSUE THREAD

**Issue by christophercr** [roelbarreto/md-steppers#11]
Hi,

Could it be possible to have the md-steppers library on NPM?

**Comment by roelbarreto** [comment]
@christophercr 
Added to npm registry, you can now `npm install md-steppers --save`
On your html add both css and js
`<link rel="stylesheet" href="/node_modules/md-steppers/dist/md-steppers.css"/>`
`<script src="/node_modules/md-steppers/dist/md-steppers.js"></script>`
Or if you use browserify just add the two file in your code for bundling
On your modules add md-steppers
`angular.module('app', [ 'ngMaterial', 'md-steppers']);`
Hope that works
Thanks

**Comment by christophercr** [comment]
Thanks! I'll try it out  ;)
