### ISSUE TITLE
Scrolling performance on iPhone 6 Plus (Safari and Chrome)

### ISSUE THREAD

**Issue by arnieraju** [roelbarreto/md-steppers#12]
When scrolling up and down on our stepper enabled form on the iPhone 6 Plus the screen appears to be flickering slightly - almost like there is a screen refresh / redraw issue occurring.  Intermittently various controls on the screen start disappearing also.

The same form without the stepper added (i.e. form sections displayed down the page) scrolls quite nicely.

We are using the following libraries in our app:
- AngularJS 1.5.3
- Angular Material 1.0.6
- MomentJS 2.13.0

When going through each step in the stepper it works well and animates very smoothly.

Wanted to see whether there is anything obvious with the combination of the above libraries that may be causing the issue.

Happy to share code and screenshots as requested.

**Comment by roelbarreto** [comment]
@anandraju  I can replicate the lag/flickering on ios-safari, I also try replacing the md-steppers with a md-tabs and it behave the same on ios-safari. The md-steppers is based on md-tabs. I am still refactoring and optimizing the code to move out from md-tabs code base.
I'll investigate the root cause and apply fix for the current release but if you can replicate the same with md-tabs then it will be angular material issue with the controls.

**Comment by roelbarreto** [comment]
@anandraju found some fix with your issue here http://stackoverflow.com/questions/9582076/how-to-prevent-scroll-lag-on-safari-mobile-ipad  
Try this solution: find any element inside md-steppers that is causing horizontal scrolling and set overflow-x to hidden.

```
md-steppers * {
        overflow-y: scroll;
        overflow-x: hidden; 
        -webkit-overflow-scrolling: touch;
    }
}
```

**Comment by arnieraju** [comment]
@ipiz Thanks so much for the quick reply and thanks for the feedback.  I'll try that out today and let you know how it goes.

**Comment by arnieraju** [comment]
I tried out that solution, however the issue is still there.  

The horizontal scrolling wasn't the issue.  Going from step to step the animation horizontally is actual silky smooth, it is the normal vertical scrolling when going up and down the form that is causing the scroll lag - i'll try and capture a video to illustrate this.

Now that I know it is potentially an angular issue that relates to the md-tabs I'll do a bit more research in that area too - will let you know what i find.

**Comment by roelbarreto** [comment]
@arnieraju How is your findings with this? THanks
