### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by jpnkicker14** [roelbarreto/md-steppers#13]
Is there a way to scroll to the top of a step's content when changing to that step? 
I'm currently using md-steppers to break up a form, but on smaller phones the user has to scroll down on step 2; then when going to step 3 the screen slides, but remains scrolled down on step 3 rather than at the top of step 3.

**Comment by roelbarreto** [comment]
@jpnkicker14  you can use `$anchorScroll`  and `$location.hash`

``` html
<div id="the-anchor">
    <md-steppers>
        <md-step>
            <!-- code here -->
            <md-button ng-click="vm.saveStepAndForward('the-anchor')">
        </md-step>
        <md-step>
            <!-- code here -->
            <md-button ng-click="vm.saveStepAndForward('the-anchor')">
        </md-step>
    </md-steppers>
</div>
```

``` javascript
//example
function gotoAnchor(x) {
    var newHash = x;
    if ($location.hash() !== newHash) {
        // set the $location.hash to `newHash` and
        // $anchorScroll will automatically scroll to it
        $location.hash(x);
    } else {
        // call $anchorScroll() explicitly,
        // since $location.hash hasn't changed
        $anchorScroll();
    }
}
vm.saveStepAndForward = saveStepAndForward;
function saveStepAndForward(anchor) {
    vm.stepBusy = true;
    gotoAnchor(anchor);
    $timeout(function () {
        vm.activeStep = 2;
        vm.steps.step1.completed = true;
        vm.steps.step2.enabled = true;
        vm.stepBusy = false;
    }, 1000);
}
```

**Comment by roelbarreto** [comment]
@jpnkicker14  here is a fiddle for you:

> https://jsfiddle.net/vcdbuyru/3/

**Comment by jpnkicker14** [comment]
@ipiz Thanks for the quick reply!
Unfortunately I couldn't get it to work quite right (possibly because of my specific layout where the steps are inside a scrollable div).  But, I found an angular scroll directive (https://github.com/oblador/angular-scroll) that ended up working just fine.
