### ISSUE TITLE
Angular Material 1.10-rc2 css and md-visually-hidden md-dummy-wrapper

### ISSUE THREAD

**Issue by Ashtlind** [roelbarreto/md-steppers#14]
The new release candidate for angular material breaks the alignment of the dummy steppers in "md-visually-hidden md-dummy-wrapper".

<img width="755" alt="screen shot 2016-05-23 at 10 43 35 am" src="https://cloud.githubusercontent.com/assets/19161455/15457777/44faacb0-20d3-11e6-97b4-4d9c943f2fb2.png">

I have resolved the issue by rolling back to 1.0.4 of the angular_material css.

**Comment by roelbarreto** [comment]
Should fix with the latest release 0.2.4 1500ceb72148acf40c88991e67f035c01a77c2a2 Thanks @Ashtlind , Kindly update your md-steppers library.
Thanks

**Comment by Ashtlind** [comment]
Great! Thanks for the speedy patch @ipiz. I will try it out shortly and let you know.

**Comment by Ashtlind** [comment]
Hey @ipiz, I have just tried it out. It seems a lot better. There is some funky stuff happening with the transitions between steps. And also the overlay seems almost opaque?

<img width="774" alt="screen shot 2016-05-24 at 9 14 04 am" src="https://cloud.githubusercontent.com/assets/19161455/15487358/080d40a2-2190-11e6-87fe-0418bbbbce83.png">

I have had a look and submitted a pull request with what fixed the issue for me. Have a look and see if you can see any issues with it.

Thanks!

**Comment by roelbarreto** [comment]
Thanks @Ashtlind  I'll make a time to review it.

**Comment by roelbarreto** [comment]
@Ashtlind https://github.com/ipiz/md-steppers/tree/0.3.0

**Comment by Ashtlind** [comment]
Thanks @ipiz looks good. Will give it a try next week.
