### ISSUE TITLE
Bower Dependencie

### ISSUE THREAD

**Issue by VerifiedOrganic** [roelbarreto/md-steppers#18]
First off really nice module, Thanks for all the work.

You should require angular as a dependence  so it will get wired in properly during minificaiton in a project.

**Comment by roelbarreto** [comment]
@DefunctExodus the dependencies on both bower and npm has been added to the current release 0.3.1 - https://github.com/ipiz/md-steppers/releases/tag/0.3.1
Thanks

**Comment by VerifiedOrganic** [comment]
Awesome looks great!

Thanks
