### ISSUE TITLE
Not able to navigate back to previous steps in IE (by clicking steps header)

### ISSUE THREAD

**Issue by dineshpandiana** [roelbarreto/md-steppers#19]
Not able to navigate back to previous steps in IE (by clicking steps header)

**Comment by roelbarreto** [comment]
@dineshpandiana  Please state the version of your IE and I'll verify. 
I replicated this in IE11 and able to navigate back using the demo  http://ipiz.herokuapp.com/demo/index.html
Thanks

**Comment by dineshpandiana** [comment]
Thanks for your reply. Am using IE11. By clicking previous button we are able to navigate back. But clicking on stepper header not able to navigate back in IE (tried in same demo). 
Please find the below screenshots.

In Chrome:
![inchrome](https://cloud.githubusercontent.com/assets/13537049/16292782/2ead53d2-3932-11e6-8fec-2fd7ad13e8fb.png)

In IE:

![iniebrowser](https://cloud.githubusercontent.com/assets/13537049/16292788/38ceed80-3932-11e6-851a-278a35cc4749.png)

**Comment by roelbarreto** [comment]
This is an svg issue, I will check the svg format, it look like it is broken on IE
THanks @dineshpandiana

**Comment by dineshpandiana** [comment]
Working now. thanks ipiz...

**Comment by dineshpandiana** [comment]
it got solved when using angular 1.4.8? Just curious to know about the fix..

**Comment by roelbarreto** [comment]
@dineshpandiana
Nope, it was fixed using the urlencoded svg in css, the angular version adjusted to 1.4.8 for lower version support, previously it was 1.5  `background: #106cc8 url("data:image/svg+xml;charset=utf8,%3Csvg fill='rgba(255,255,255,0.87)' height='16' viewBox='0 0 24 24' width='16' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3Cpath d='M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z'/%3E%3C/svg%3E") no-repeat center center; }`
