### ISSUE TITLE
Add steps dynamically

### ISSUE THREAD

**Issue by ringil-21** [roelbarreto/md-steppers#22]
Is it possible to add steps after md-steppers has been initialized? 
In my use case I want to add the next step based on the selection made in another step. Therefore the stepper can have a various number of steps.

**Comment by roelbarreto** [comment]
It allow it but there are some bugs that it doesn't bind events on newly created tabs will check it, thanks @alois-wever 
See it here https://jsfiddle.net/ipiz/vcdbuyru/30/

**Comment by ringil-21** [comment]
Thanks @ipiz for your quick response and example. It was very helpful! Have it already up and running in my app.
Hope you can easily fix the bugs.
Cheers

**Comment by venkataramanareddy** [comment]
Is it possible to add the step in middle of existing steps. The numbers are not getting changed in the progress bar with the above example.
When we disable the step, still it will be shown in the progress bar. How can we hide the particular step in progress bar based on condition?

**Comment by roelbarreto** [comment]
Unfortunately it still doesn't support dynamically inserting steps. As my review it is not documented on Material Steppers. Better to have optional steps that is already there or use enable disable steps on applicable situation.
Hope this will be helpfull

**Comment by venkataramanareddy** [comment]
Thanks for your response @ipiz.

**Comment by depyronick** [comment]
@venkataramanareddy well simply change `'stepindex="{{::$index+1}}" '` with `'stepindex="{{step.getIndex()+1}}" '` and handle showing tab by using `ng-if`
