### ISSUE TITLE
alternative labels 

### ISSUE THREAD

**Issue by menasbeshay** [roelbarreto/md-steppers#24]
i searched alot for hot to use the stepper with alternative labels without success and also documentation isn't reach enough to tell me how to do it.
please advice.

**Comment by roelbarreto** [comment]
You can try this https://jsfiddle.net/vcdbuyru/63/ for the meantime but it only works for short labels.

**Comment by massi08** [comment]
Hello I did it first by adding `layout="column" layout-fill`to`<md-step-label-wrapper>` then in `.md-step` css i changed `white-space` to `white-space: normal;`
![image](https://cloud.githubusercontent.com/assets/17096495/19233420/a8d0c870-8ee5-11e6-99a9-a066821ab6df.png)
