### ISSUE TITLE
Usage in a md-dialog (bug with ie11)

### ISSUE THREAD

**Issue by Klotair** [roelbarreto/md-steppers#27]
Hello,
Nice component :) 

I'm having an issue using md-steppers in a md-dialog from angular-md. 
The content position of the first step seems to be getting from the left side of the window rather than the left side of the md-dialog.  (only on ie11) 

When inspecting it with ie11 dev tools, the css is good but it is rendered too early when the md-dialog is not correctly displayed. Is there a way to delayed the rendering of md-steppers ? I think it should do the trick.

Thanks.

**Comment by Klotair** [comment]
Hi again,

I resolved this by simply adding the ng-cloak directive to the md-dialog element.

**Comment by roelbarreto** [comment]
Thanks @Klotair
