### ISSUE TITLE
Steppers not taking full height

### ISSUE THREAD

**Issue by hammadmansuri** [roelbarreto/md-steppers#31]
Thanks for this awesome work @ipiz !! 

I am trying to make steppers to take full available height. I tried to give flex to parents, but no success.

I want something like this... 
![stepper prob](https://user-images.githubusercontent.com/3831997/29066642-7b0f5b8a-7c4d-11e7-9171-fde3583571ae.png)

Here, i tried. [Link](https://jsfiddle.net/hammadmansuri/njmrma3m/)

Somehow, **md-steppers-template** div is not taking full height. What i am missing ?

Thanks in advance!

**Comment by roelbarreto** [comment]
@hammadmansuri 
I added some css to achieve your goal making div full height
https://jsfiddle.net/njmrma3m/1/

**Comment by hammadmansuri** [comment]
Hello @ipiz, Appreciating your quick response. You hit on a perfect point. It's working as expected.

Thanks a Ton.!!
