### ISSUE TITLE
Feature requests : Vertical steppers

### ISSUE THREAD

**Issue by stunaz** [roelbarreto/md-steppers#7]

**Comment by ighormartins** [comment]
+1

**Comment by manoharnv** [comment]
+1

**Comment by odyright** [comment]
Hello, i'm interested, so, the release date of vertical stepper?

**Comment by roelbarreto** [comment]
Hi @odyright we have a new branch for its development but not yet progressing because I'm a bit bussy. I'll try finish it untill the end of July.Thanks
This is not yet a release candidate since I'm still experimenting on it.
https://github.com/ipiz/md-steppers/tree/major-refactor

**Comment by hammadmansuri** [comment]
Hello @ipiz , md-stepper works like charm. In my project, there is a need of vertical stepper. So, just want to check with you - is there any update regarding vertical steppers ?

**Comment by roelbarreto** [comment]
Doesn't have time yet to work on this, but I'll try if I can progress it.
Thanks @hammadmansuri
